//
// Created by huan on 3/22/17.
//

#ifndef CPU_SCHEDULING_SIMULATOR_ALGO_PRIORITY_H
#define CPU_SCHEDULING_SIMULATOR_ALGO_PRIORITY_H


class algo_PRIORITY {

};


#endif //CPU_SCHEDULING_SIMULATOR_ALGO_PRIORITY_H
